"""One-off migration: fix off-by-one-session labeling bug in universe ticker bars.

A prior ad-hoc Yahoo backfill loaded daily bars for 8 universe tickers
with timestamps offset by one trading session — every stored "day N"
bar contained day N-1's close. Confirmed on 2026-04-15 by comparing
stored close values against fresh Yahoo data at varying depths (99%+
mismatch across the full 5-year history; only today's new bars match).

Scope: NVDA, META, QQQ, AAPL, MSFT, AMD, GOOGL, IWM.

Not affected (verified clean, untouched):
  - TSLA (100% match)
  - SPY, HYG, TLT, VIX (100% match)
  - XLB, XLC, XLE, XLF, XLI, XLP, XLRE, XLU, XLV, XLY (100% match)
  - XLK (83% match — 43 pre-existing discrepancies from a different
    source, unrelated to this bug and out of scope).

Operations performed, all inside a single sqlite transaction:
  1. DELETE every bar for the 8 affected tickers.
  2. Re-fetch 5y of daily bars from Yahoo (auto_adjust=False, raw closes).
  3. INSERT the new bars.
  4. DELETE every position (backtest `bt:` runs only — no paper trades
     exist for these tickers) for the 8 affected tickers. Runs were
     built on shifted data and must be regenerated by the evolver.
  5. DELETE every evolver_proposals row for the 8 affected tickers.
  6. Reset ticker_state for the 8: phase='discovering', iteration_count=0,
     plateau_counter=0, best_strategy_id=NULL, best_pf_is=NULL,
     best_pf_oos=NULL, paper_started_at=NULL, paper_trade_count=0,
     verdict_at=NULL, updated_at=now. `cumulative_llm_usd` is PRESERVED
     intentionally — that spend actually happened.

After the migration the evolver must be re-run on each affected ticker
so that new strategies are selected against correct historical data.

Run with:
    python scripts/migrate_universe_relabel_fix.py

Dry run with:
    python scripts/migrate_universe_relabel_fix.py --dry-run

The script verifies a timestamped backup exists in cache/ before
running and refuses to continue without one. `cp cache/bullbot.db
cache/bullbot.db.bak.$(date +%Y%m%d-%H%M%S)` before invoking.
"""
from __future__ import annotations

import argparse
import logging
import sqlite3
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bullbot import config
from bullbot.data import daily_refresh

AFFECTED: tuple[str, ...] = (
    "NVDA",
    "META",
    "QQQ",
    "AAPL",
    "MSFT",
    "AMD",
    "GOOGL",
    "IWM",
)


def _require_backup() -> None:
    """Fail fast if no recent DB backup exists in cache/."""
    cache_dir = Path(config.DB_PATH).parent
    backups = sorted(cache_dir.glob("bullbot.db.bak.*"))
    if not backups:
        raise SystemExit(
            "no cache/bullbot.db.bak.* found — refusing to run destructive "
            "migration without a backup. copy cache/bullbot.db first."
        )
    log.info("found backup: %s", backups[-1])


def _delete_bars(conn: sqlite3.Connection) -> int:
    ph = ",".join("?" * len(AFFECTED))
    cur = conn.execute(
        f"DELETE FROM bars WHERE ticker IN ({ph}) AND timeframe='1d'",
        AFFECTED,
    )
    return cur.rowcount


def _delete_positions(conn: sqlite3.Connection) -> int:
    ph = ",".join("?" * len(AFFECTED))
    cur = conn.execute(
        f"DELETE FROM positions WHERE ticker IN ({ph})",
        AFFECTED,
    )
    return cur.rowcount


def _delete_proposals(conn: sqlite3.Connection) -> int:
    ph = ",".join("?" * len(AFFECTED))
    cur = conn.execute(
        f"DELETE FROM evolver_proposals WHERE ticker IN ({ph})",
        AFFECTED,
    )
    return cur.rowcount


def _reset_ticker_state(conn: sqlite3.Connection) -> int:
    ph = ",".join("?" * len(AFFECTED))
    now = int(time.time())
    cur = conn.execute(
        f"""UPDATE ticker_state
            SET phase='discovering',
                iteration_count=0,
                plateau_counter=0,
                best_strategy_id=NULL,
                best_pf_is=NULL,
                best_pf_oos=NULL,
                paper_started_at=NULL,
                paper_trade_count=0,
                verdict_at=NULL,
                updated_at=?
            WHERE ticker IN ({ph})""",
        (now, *AFFECTED),
    )
    return cur.rowcount


def _refetch_bars(conn: sqlite3.Connection) -> dict[str, int]:
    # commit=False: the migration owns the transaction boundary
    return daily_refresh.refresh_all_bars(conn, list(AFFECTED), period="5y", commit=False)


def _verify_against_yahoo(conn: sqlite3.Connection) -> None:
    """Sanity check: confirm each affected ticker matches Yahoo raw closes at ~100%."""
    import yfinance as yf

    conn.row_factory = sqlite3.Row
    for ticker in AFFECTED:
        df = yf.Ticker(ticker).history(period="5y", interval="1d", auto_adjust=False)
        truth = {idx.strftime("%Y-%m-%d"): round(row["Close"], 2) for idx, row in df.iterrows()}
        rows = conn.execute(
            "SELECT date(ts, 'unixepoch') AS d, close FROM bars "
            "WHERE ticker=? AND timeframe='1d'",
            (ticker,),
        ).fetchall()
        exact = mismatch = no_truth = 0
        for r in rows:
            if r["d"] not in truth:
                no_truth += 1
                continue
            if round(r["close"], 2) == truth[r["d"]]:
                exact += 1
            else:
                mismatch += 1
        comparable = exact + mismatch
        pct = 100.0 * exact / max(1, comparable)
        status = "OK" if pct >= 99.0 else "FAIL"
        log.info(
            "verify %s: %d bars, %d exact, %d mismatch, %d no_truth, %.1f%% match [%s]",
            ticker,
            len(rows),
            exact,
            mismatch,
            no_truth,
            pct,
            status,
        )
        if pct < 99.0:
            raise RuntimeError(
                f"post-migration verification failed for {ticker}: "
                f"only {pct:.1f}% match"
            )


log = logging.getLogger("migrate_universe_relabel_fix")


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="report what would happen without mutating")
    args = parser.parse_args(argv)

    _require_backup()

    # isolation_level=None → fully manual transaction control.
    conn = sqlite3.connect(str(config.DB_PATH), isolation_level=None)
    conn.row_factory = sqlite3.Row
    in_txn = False
    try:
        conn.execute("BEGIN")
        in_txn = True

        bars_deleted = _delete_bars(conn)
        positions_deleted = _delete_positions(conn)
        proposals_deleted = _delete_proposals(conn)
        state_reset = _reset_ticker_state(conn)

        log.info(
            "pre-refetch delete counts: bars=%d, positions=%d, proposals=%d, ticker_state_reset=%d",
            bars_deleted,
            positions_deleted,
            proposals_deleted,
            state_reset,
        )

        log.info("re-fetching 5y bars for %d tickers from Yahoo...", len(AFFECTED))
        refetch_counts = _refetch_bars(conn)
        total_bars = sum(refetch_counts.values())
        log.info("re-fetched %d bars total", total_bars)
        for t, n in sorted(refetch_counts.items()):
            log.info("  %s: %d bars", t, n)
        failed = [t for t, n in refetch_counts.items() if n == 0]
        if failed:
            raise RuntimeError(f"re-fetch failed for tickers: {failed}")

        _verify_against_yahoo(conn)

        if args.dry_run:
            log.info("--dry-run set; rolling back all changes")
            conn.execute("ROLLBACK")
            in_txn = False
            return 0

        conn.execute("COMMIT")
        in_txn = False
        log.info("migration COMMITTED")
        return 0
    except Exception:
        log.exception("migration FAILED — rolling back")
        if in_txn:
            try:
                conn.execute("ROLLBACK")
            except sqlite3.OperationalError as e:
                log.warning("rollback skipped: %s", e)
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
